### ISSUE TITLE
Confusing that this repo duplicates GoogleCloudPlatform/cloud-run-hello

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/buildpack-samples#1]
I think https://github.com/GoogleCloudPlatform/buildpack-samples/tree/master/sample-go should not copy the Cloud Run quickstart but use a simple naive Go hello world. 

The fact that the README claims that is the source of the gcr.io/cloudrun/hello image is misleading, as https://github.com/GoogleCloudPlatform/cloud-run-hello is actually the source.

**Comment by jamesward** [comment]
Whoops.  Yeah, I'll clean that up.
