### ISSUE TITLE
List pack commands in samples

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/buildpack-samples#3]
e.g. https://github.com/GoogleCloudPlatform/buildpack-samples/blob/e050ffabe8a4c319ad5022d9a747b79a0c737a14/sample-node/README.md talks about `npm install` `npm start` which isn't relevant to buildpacks.

Other languages are in the same boat too.

**Comment by jamesward** [comment]
The non-pack commands are important for local development, but yeah I should add the pack commands too.
