### ISSUE TITLE
Node buildpack sample doesn't work in Cloud Shell Editor

### ISSUE THREAD

**Issue by abbycar** [GoogleCloudPlatform/buildpack-samples#9]
Part of the [Node buildpacks sample](https://github.com/GoogleCloudPlatform/buildpack-samples/tree/master/sample-node) doesn't run in Cloud Shell Editor due to the port it's running on. This app wants to run on port 3000, but Cloud Shell Editor uses port 3000.

Can the port be switched to 8080?

**Comment by jamesward** [comment]
Oh. Interesting that they are using `3000`.  Want to send a PR to fix that?

**Comment by abbycar** [comment]
Done!
https://github.com/GoogleCloudPlatform/buildpack-samples/pull/10

**Comment by jamesward** [comment]
Thank you!
